### ISSUE TITLE
Could your update "natestrauser:select2" to 4?

### ISSUE THREAD

**Issue by thearabbit** [zimme/meteor-select2-bootstrap3-css#5]
Could your update "natestrauser:select2" to 4?

**Comment by zimme** [comment]
I'll try and get this done tonight.

**Comment by zimme** [comment]
So there's a new bootstrap3 theme for select2 `4.0.0`, it's not the same as `select2-bootstrap-css` and I feel it should be it's own package.

https://github.com/select2/select2-bootstrap-theme

I'll try and get that package done this weekend unless there isn't one already.

@vieko, I saw that you forked this package to update the select2 version, maybe you would be interested in creating the package for `select2-bootstrap-theme`?

**Comment by thearabbit** [comment]
Thanks for your reply.

**Comment by vieko** [comment]
hey @zimme, I saw that. Might give it a try when my queue clears... pretty busy with work right now :)
